#!/bin/sh

#Install Fluent Theme https://www.youtube.com/watch?v=sLETZzOieoA&t=363s

cd;
mkdir git;
cd git;
git clone https://github.com/vinceliuice/Fluent-kde.git;
git clone https://github.com/vinceliuice/Fluent-gtk-theme.git;
git clone https://github.com/vinceliuice/Fluent-icon-theme.git;
cd Fluent-kde;
./install.sh -t purple -c dark --rounded
cd ..
cd Fluent-gtk-theme;
./install.sh -t purple -c dark --rounded -s -i manjaro 
